name: Extract boots

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'link of full OxygenOS/ColorOS file'
        required: true
        type: string

jobs:
  boot-extract:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Extract boots
      run: |
        wget -q https://github.com/PRO-2684/pay10ad-dumper/releases/download/v0.1.3/pay10ad-dumper-v0.1.3-x86_64-unknown-linux-gnu.tar.gz
        tar -xvf pay10ad-dumper-v0.1.3-x86_64-unknown-linux-gnu.tar.gz ./pay10ad-dumper
        rm pay10ad-dumper-v0.1.3-x86_64-unknown-linux-gnu.tar.gz
        ./pay10ad-dumper -u curl -p boot -p init_boot -p vendor_boot ${{ github.event.inputs.file_url }}
        # ./output/*.img

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install -r ./scripts/requirements.txt

    - name: Parse metadata
      id: parse-metadata
      run: |
        python3 ./scripts/metadata.py ${{ github.event.inputs.file_url }}

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.parse-metadata.outputs.version_name }}
        body_path: ./output/note.md
        files: |
          ./output/boot.img
          ./output/init_boot.img
          ./output/vendor_boot.img
